export { default as logo } from "../assets/logo.png"
export { default as github } from "../assets/tech/github.svg";
export { default as tailwind } from "../assets/tech/tailwind.png";
export { default as postman } from "../assets/postman.svg"
export { default as external } from "../assets/external.svg"
export { default as code } from "../assets/code.svg"
export { default as gmail } from "../assets/gmail.svg"
export { default as linkedin } from "../assets/linkedin.svg"
export { default as discord } from "../assets/discord.svg"
export { default as contact } from "../assets/contact.gif"
export { default as more } from "../assets/more.svg"
export { default as user } from "../assets/user.png"
export { default as projects } from "../assets/projects.png"
export { default as tech } from "../assets/tech.png"
export { default as contact_icon } from "../assets/contact-sidebar.png"
export { default as experiences } from "../assets/experiences.png"
export { default as githublogo} from "../assets/githubhome.svg"
export {default as OpportuneX} from "../assets/projects/OpportuneX.png"
export {default as WhatsAppBot} from "../assets/projects/WhatsAppBot.png"
export {default as Talentd} from "../assets/talentd.png"
export {default as Leetcode} from "../assets/Leetcode.png"
export {default as codechef} from "../assets/codechef.png"
